=== jpeddicord/jobservice/doc/sls.dtd
<!-- Service-Level Settings DTD -->
<!-- Distributed under the license of the jobservice project. -->

<!ELEMENT settings (setting+)>
<!ELEMENT setting (description,data?,values?)>
<!ATTLIST setting name CDATA #REQUIRED>
<!ATTLIST setting type (bool|int|float|str|label|choice|file|dir|user|group|exec) #REQUIRED>

<!ELEMENT description (#PCDATA)>

<!ELEMENT data (parse*)>
<!ATTLIST data val CDATA #IMPLIED>

<!ELEMENT parse (#PCDATA)>
<!ATTLIST parse file CDATA #IMPLIED>
<!ATTLIST parse after CDATA #IMPLIED>
<!ATTLIST parse get CDATA #IMPLIED>
<!ATTLIST parse set CDATA #IMPLIED>

<!ELEMENT values (value*)>
<!ATTLIST values min CDATA #IMPLIED>
<!ATTLIST values max CDATA #IMPLIED>
<!ATTLIST values sep CDATA #IMPLIED>
<!ATTLIST values exist CDATA #IMPLIED>
<!ATTLIST values useid CDATA #IMPLIED>

<!ELEMENT value (raw?,description?)>
<!ATTLIST value name CDATA #REQUIRED>

<!ELEMENT raw (#PCDATA)>

=== jpeddicord/jobservice/sls/pulseaudio.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE settings PUBLIC
 "-//Ubuntu//DTD JobService Service-Level Settings 0.1//EN"
 "http://people.ubuntu.com/~jpeddicord/SLS/0.1/sls.dtd">
<settings>
    <setting name="system" type="bool">
        <description>System mode</description>
        <file>/etc/default/pulseaudio</file>
        <parse>PULSEAUDIO_SYSTEM_START=%s</parse>
        <values>
            <value name="true">1</value>
            <value name="false">0</value>
        </values>
    </setting>
</settings>

=== jpeddicord/jobservice/sls/ufw.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE settings PUBLIC
 "-//Ubuntu//DTD JobService Service-Level Settings 0.1//EN"
 "http://people.ubuntu.com/~jpeddicord/SLS/0.1/sls.dtd">
<settings>
    <setting name="ipv6" type="bool">
        <description>Use IPV6</description>
        <file>/etc/default/ufw</file>
        <parse>IPV6=%s</parse>
        <values>
            <value name="true">yes</value>
            <value name="false">no</value>
        </values>
    </setting>
    <setting name="default_input_policy" type="choice">
        <description>Default inbound policy</description>
        <file>/etc/default/ufw</file>
        <parse>DEFAULT_INPUT_POLICY="%s"</parse>
        <values>
            <value name="drop" description="Drop">DROP</value>
            <value name="accept" description="Accept">ACCEPT</value>
            <value name="accept_no_track" description="Accept (no connection tracking)">ACCEPT_NO_TRACK</value>
            <value name="reject" description="Reject">REJECT</value>
        </values>
    </setting>
    <setting name="default_output_policy" type="choice">
        <description>Default outbound policy</description>
        <file>/etc/default/ufw</file>
        <parse>DEFAULT_OUTPUT_POLICY="%s"</parse>
        <values>
            <value name="drop" description="Drop">DROP</value>
            <value name="accept" description="Accept">ACCEPT</value>
            <value name="accept_no_track" description="Accept (no connection tracking)">ACCEPT_NO_TRACK</value>
            <value name="reject" description="Reject">REJECT</value>
        </values>
    </setting>
</settings>

=== jpeddicord/jobservice/sls/kerneloops.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE settings PUBLIC
 "-//Ubuntu//DTD JobService Service-Level Settings 0.1//EN"
 "http://people.ubuntu.com/~jpeddicord/SLS/0.1/sls.dtd">
<settings>
    <setting type="bool" name="enable">
        <description>Enable kernel crash reporting</description>
        <file>/etc/default/kerneloops</file>
        <parse>enabled=%s</parse>
        <values>
            <value name="true">
                <data>1</data>
            </value>
            <value name="false">
                <data>0</data>
            </value>
        </values>
    </setting>
</settings>
